/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.0.9 (4.0)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
)

// checks if the DeviceWithConfigContextStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeviceWithConfigContextStatus{}

// DeviceWithConfigContextStatus struct for DeviceWithConfigContextStatus
type DeviceWithConfigContextStatus struct {
	Value *DeviceWithConfigContextStatusValue `json:"value,omitempty"`
	Label *DeviceStatusLabel `json:"label,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DeviceWithConfigContextStatus DeviceWithConfigContextStatus

// NewDeviceWithConfigContextStatus instantiates a new DeviceWithConfigContextStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeviceWithConfigContextStatus() *DeviceWithConfigContextStatus {
	this := DeviceWithConfigContextStatus{}
	return &this
}

// NewDeviceWithConfigContextStatusWithDefaults instantiates a new DeviceWithConfigContextStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeviceWithConfigContextStatusWithDefaults() *DeviceWithConfigContextStatus {
	this := DeviceWithConfigContextStatus{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *DeviceWithConfigContextStatus) GetValue() DeviceWithConfigContextStatusValue {
	if o == nil || IsNil(o.Value) {
		var ret DeviceWithConfigContextStatusValue
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceWithConfigContextStatus) GetValueOk() (*DeviceWithConfigContextStatusValue, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *DeviceWithConfigContextStatus) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given DeviceWithConfigContextStatusValue and assigns it to the Value field.
func (o *DeviceWithConfigContextStatus) SetValue(v DeviceWithConfigContextStatusValue) {
	o.Value = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *DeviceWithConfigContextStatus) GetLabel() DeviceStatusLabel {
	if o == nil || IsNil(o.Label) {
		var ret DeviceStatusLabel
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceWithConfigContextStatus) GetLabelOk() (*DeviceStatusLabel, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *DeviceWithConfigContextStatus) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given DeviceStatusLabel and assigns it to the Label field.
func (o *DeviceWithConfigContextStatus) SetLabel(v DeviceStatusLabel) {
	o.Label = &v
}

func (o DeviceWithConfigContextStatus) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeviceWithConfigContextStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DeviceWithConfigContextStatus) UnmarshalJSON(data []byte) (err error) {
	varDeviceWithConfigContextStatus := _DeviceWithConfigContextStatus{}

	err = json.Unmarshal(data, &varDeviceWithConfigContextStatus)

	if err != nil {
		return err
	}

	*o = DeviceWithConfigContextStatus(varDeviceWithConfigContextStatus)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "value")
		delete(additionalProperties, "label")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDeviceWithConfigContextStatus struct {
	value *DeviceWithConfigContextStatus
	isSet bool
}

func (v NullableDeviceWithConfigContextStatus) Get() *DeviceWithConfigContextStatus {
	return v.value
}

func (v *NullableDeviceWithConfigContextStatus) Set(val *DeviceWithConfigContextStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableDeviceWithConfigContextStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableDeviceWithConfigContextStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeviceWithConfigContextStatus(val *DeviceWithConfigContextStatus) *NullableDeviceWithConfigContextStatus {
	return &NullableDeviceWithConfigContextStatus{value: val, isSet: true}
}

func (v NullableDeviceWithConfigContextStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeviceWithConfigContextStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


