/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.0.9 (4.0)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// DeviceWithConfigContextRequestStatus * `offline` - Offline * `active` - Active * `planned` - Planned * `staged` - Staged * `failed` - Failed * `inventory` - Inventory * `decommissioning` - Decommissioning
type DeviceWithConfigContextRequestStatus string

// List of DeviceWithConfigContextRequest_status
const (
	DEVICEWITHCONFIGCONTEXTREQUESTSTATUS_OFFLINE         DeviceWithConfigContextRequestStatus = "offline"
	DEVICEWITHCONFIGCONTEXTREQUESTSTATUS_ACTIVE          DeviceWithConfigContextRequestStatus = "active"
	DEVICEWITHCONFIGCONTEXTREQUESTSTATUS_PLANNED         DeviceWithConfigContextRequestStatus = "planned"
	DEVICEWITHCONFIGCONTEXTREQUESTSTATUS_STAGED          DeviceWithConfigContextRequestStatus = "staged"
	DEVICEWITHCONFIGCONTEXTREQUESTSTATUS_FAILED          DeviceWithConfigContextRequestStatus = "failed"
	DEVICEWITHCONFIGCONTEXTREQUESTSTATUS_INVENTORY       DeviceWithConfigContextRequestStatus = "inventory"
	DEVICEWITHCONFIGCONTEXTREQUESTSTATUS_DECOMMISSIONING DeviceWithConfigContextRequestStatus = "decommissioning"
)

// All allowed values of DeviceWithConfigContextRequestStatus enum
var AllowedDeviceWithConfigContextRequestStatusEnumValues = []DeviceWithConfigContextRequestStatus{
	"offline",
	"active",
	"planned",
	"staged",
	"failed",
	"inventory",
	"decommissioning",
}

func (v *DeviceWithConfigContextRequestStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := DeviceWithConfigContextRequestStatus(value)
	for _, existing := range AllowedDeviceWithConfigContextRequestStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid DeviceWithConfigContextRequestStatus", value)
}

// NewDeviceWithConfigContextRequestStatusFromValue returns a pointer to a valid DeviceWithConfigContextRequestStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewDeviceWithConfigContextRequestStatusFromValue(v string) (*DeviceWithConfigContextRequestStatus, error) {
	ev := DeviceWithConfigContextRequestStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for DeviceWithConfigContextRequestStatus: valid values are %v", v, AllowedDeviceWithConfigContextRequestStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v DeviceWithConfigContextRequestStatus) IsValid() bool {
	for _, existing := range AllowedDeviceWithConfigContextRequestStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to DeviceWithConfigContextRequest_status value
func (v DeviceWithConfigContextRequestStatus) Ptr() *DeviceWithConfigContextRequestStatus {
	return &v
}

type NullableDeviceWithConfigContextRequestStatus struct {
	value *DeviceWithConfigContextRequestStatus
	isSet bool
}

func (v NullableDeviceWithConfigContextRequestStatus) Get() *DeviceWithConfigContextRequestStatus {
	return v.value
}

func (v *NullableDeviceWithConfigContextRequestStatus) Set(val *DeviceWithConfigContextRequestStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableDeviceWithConfigContextRequestStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableDeviceWithConfigContextRequestStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeviceWithConfigContextRequestStatus(val *DeviceWithConfigContextRequestStatus) *NullableDeviceWithConfigContextRequestStatus {
	return &NullableDeviceWithConfigContextRequestStatus{value: val, isSet: true}
}

func (v NullableDeviceWithConfigContextRequestStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeviceWithConfigContextRequestStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
